name: Test backend
on:
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ./backend

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        cache: 'pip' # caching pip dependencies
    - name: Install requirements
      run: pip install -r ./tests/requirements.txt
    - name: Add credentials
      run:  | 
          mkdir ~/.aws
          echo [default] >> ~/.aws/config
          echo aws_access_key_id=${{ secrets.AWS_LAMBDA_ACCESS_KEY_ID }} >> ~/.aws/config
          echo aws_secret_access_key=${{ secrets.AWS_LAMBDA_SECRET_ACCESS_KEY }} >> ~/.aws/config
          echo region=eu-central-1 >> ~/.aws/config
    - name: Run tests
      run: py.test ./tests/test_app.py
