name: Upload a folder to S3

on:
  workflow_dispatch:
  push:
    branches:
    - "*"

defaults:
  run:
    working-directory: ./backend

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        cache: 'pip' # caching pip dependencies
    - name: Install requirements
      run: pip install -r ./tests/requirements.txt
    - name: Add credentials
      run:  | 
          $ mkdir ~/.aws
          $ cat >> ~/.aws/config
          [default]
          aws_access_key_id=${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          aws_secret_access_key=${{ secrets.AWS_S3_ACCESS_KEY }}
          region=eu-central-1
    - name: Deploy
      run: chalice deploy --stage prod
