name: Upload a folder to S3

on:
  workflow_dispatch:
  push:
    branches:
    - "*"

defaults:
  run:
    working-directory: ./frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: npm install
    
    - name: Build static files
      run: npm run build
        
    - name: Copy folder to s3
      uses: shallwefootball/s3-upload-action@master
      with:
        aws_key_id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
        aws_bucket: 's3://frontend-deployment-bucket/out'
        source_dir: '/home/runner/work/devops-group-16/devops-group-16/frontend/out'
        destination_dir: '/out'
