name: Jest and React Testing Library

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      working-directory: frontend
      run: npm install

    - name: Run tests
      working-directory: frontend
      run: npm test
