name: Test backend
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        cache: 'pip' # caching pip dependencies
    - name: Install requirements
      run: pip install -r backend/tests/requirements.txt
    - name: Run tests
      run: py.test backend/tests/test_app.py
