name: Nightly Test

on:
  schedule:
    - cron: '0 0 * * *' # Run nightly at midnight
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ./e2e

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install dependencies
      run: npm install
      
    - name: Run testcafe tests
      run: npm run test