name: Nightly Test

on:
  schedule:
    - cron: '0 0 * * *' # Run nightly at midnight
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ./e2e

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install dependencies
      run: npm install
      
    - name: Run testcafe tests
      env:
        TEST_QUESTION_LINK: ${{ secrets.E2E_QUESTION_URL}}
        TEST_QUESTION_USERNAME: ${{secrets.E2E_USERNAME}}
        TEST_QUESTION_PASS: ${{ secrets.E2E_PASSWORD}}
      run: npm run test
